server:
  port: 8081
  servlet:
    context-path: /jdgl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiudian?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.ysd.demo.entity
  mapper-locations:
  - classpath:mapper/*.xml
logging:
  level: 
    root: warn
    com.ysd.demo.mapper: trace
  pattern:
    console: '%p%m%n'
  